# Copyright 2016, 2017 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

python: "2.7"

os:
  - linux
  - osx

branches:
  only:
    - master
    - develop

env:
  matrix:
    - BOGUS_JOB=true

matrix:

  exclude:
    - env: BOGUS_JOB=true

  include:
    - os: linux
      env: TOOLSET=gcc COMPILER=g++ CXXSTD=03

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.7 CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.8 CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-4.9 CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-5 CXXSTD=03,11,14
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=03,11
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=14,1z
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=03,11 CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-6 CXXSTD=14,1z CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=03,11 CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-7 CXXSTD=14,1z CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-8 CXXSTD=03,11 CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=gcc COMPILER=g++-8 CXXSTD=14,1z CXXSTD_DIALECT=cxxstd-dialect=gnu
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test

    - os: linux
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.5 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.6 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.6
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.7 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.8 CXXSTD=14,1z
      addons:
        apt:
          packages:
            - clang-3.8
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=03,11
      addons:
        apt:
          packages:
            - clang-3.9
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: linux
      env: TOOLSET=clang COMPILER=clang++-3.9 CXXSTD=14,1z
      addons:
        apt:
          packages:
            - clang-3.9
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=03,11
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=14,1z
      osx_image: xcode8.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode8.2

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode8.1

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode8.0

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode7.3

    - os: osx
      env: TOOLSET=clang COMPILER=clang++ CXXSTD=11
      osx_image: xcode6.4

install:
  - cd ..
  - git clone -b $TRAVIS_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/build
  - git submodule update --init libs/config
  - git submodule update --init libs/core
  - git submodule update --init libs/container_hash
  - git submodule update --init libs/detail
  - git submodule update --init libs/smart_ptr
  - git submodule update --init libs/predef
  - git submodule update --init libs/assert
  - git submodule update --init libs/throw_exception
  - git submodule update --init libs/mpl
  - git submodule update --init libs/type_traits
  - git submodule update --init libs/static_assert
  - git submodule update --init libs/integer
  - git submodule update --init libs/preprocessor
  - git submodule update --init libs/functional
  - git submodule update --init libs/program_options
  - git submodule update --init libs/chrono
  - git submodule update --init libs/system
  - git submodule update --init libs/thread
  - git submodule update --init libs/winapi
  - git submodule update --init libs/move
  - git submodule update --init libs/date_time
  - git submodule update --init libs/ratio
  - git submodule update --init libs/iterator
  - git submodule update --init libs/range
  - git submodule update --init libs/any
  - git submodule update --init libs/concept_check
  - git submodule update --init libs/array
  - git submodule update --init libs/timer
  - git submodule update --init libs/bind
  - git submodule update --init libs/utility
  - git submodule update --init libs/io
  - git submodule update --init libs/intrusive
  - git submodule update --init libs/container
  - git submodule update --init libs/tuple
  - git submodule update --init libs/exception
  - git submodule update --init libs/function
  - git submodule update --init libs/type_index
  - git submodule update --init libs/lexical_cast
  - git submodule update --init libs/numeric
  - git submodule update --init libs/math
  - git submodule update --init libs/tokenizer
  - git submodule update --init libs/optional
  - git submodule update --init libs/atomic
  - git submodule update --init libs/rational
  - git submodule update --init libs/algorithm
  - cp -r $TRAVIS_BUILD_DIR/* libs/regex
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
    echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - IFS=','
  - for CXXLOCAL in $CXXSTD; do  (cd libs/config/test && ../../../b2 config_info_travis_install toolset=$TOOLSET cxxstd=$CXXLOCAL $CXXSTD_DIALECT && echo With Standard Version $CXXLOCAL && ./config_info_travis && rm ./config_info_travis)  done
  - unset IFS
  - ./b2 -j3 libs/regex/test toolset=$TOOLSET cxxstd=$CXXSTD $CXXSTD_DIALECT

notifications:
  email:
    on_success: always
